version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - PORT=3000
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - '.env.demo:/app/.env'
