export const EXCEPTION_HANDLER_NAME = 'ExceptionsHandler';
export const ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
export const UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS';
export const DUPLICATE_ENTRY = 'DUPLICATE_ENTRY';
